[package]
name = "flow-web"
version = "0.2.4"
edition = "2024"
authors = ["Andreas Widen <aw@luflow.net>"]
description = "flow-web is a program that will allow you to generate a static website."
license = "AGPL-3.0-or-later"
homepage = "https://luflow.net/"
repository = "https://git.luflow.net/hfsoulz/flow-web.git"
readme = "README.md"
keywords = ["static-site-generator", "website-generator"]
exclude = [".github", ".forgejo", ".gitignore", "*.log", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "SECURITY.md"]

[dependencies]
async-recursion = "1.1.1"
chrono = "0.4.45"
fern = "0.7.1"
humantime = "2.4.0"
log = "0.4.33"
markdown = "1.0.0"
regex = "1.13.1"
rich_rust = "0.2.2"
sailfish = "0.11.3"
tokio = { version = "1.53.1", features = ["macros", "fs", "io-util", "rt-multi-thread"] }
